language: java
jdk:
  - oraclejdk8
env:
  - chromeBinaryPath=/home/travis/build/twosigma/beaker-notebook/chrome-linux/chrome
sudo: required
services:
- docker
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip"
  - "curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip && unzip chromedriver.zip"
  - "sudo add-apt-repository --yes ppa:chris-lea/zeromq"
  - "sudo add-apt-repository --yes ppa:marutter/rrutter"
  - "curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -"
  - "gem install sass"
  - "sudo apt-get install -y nodejs"
  - 'ln -s /usr/bin/node /home/travis/build/twosigma/beaker-notebook/'
  - 'ln -s /usr/bin/npm /home/travis/build/twosigma/beaker-notebook/'
install:
  - travis_retry npm install ./core/
  - travis_retry npm install ./test/
before_script:
  - export PATH=/home/travis/build/twosigma/beaker-notebook:$PATH
  - sudo apt-get install -y libzmq3-dbg libzmq3-dev libzmq3
  - sudo apt-get install -y python-pip python-dev
  - sudo pip install ipython==3.2.1 jinja2 tornado
  - sudo pip install pyzmq
  - sudo apt-get install -y python-matplotlib python-scipy python-pandas
